'use strict';
const files = 'abcdefgh';
const symbols = {K:'♚',Q:'♛',R:'♜',B:'♝',N:'♞',P:'♟',k:'♚',q:'♛',r:'♜',b:'♝',n:'♞',p:'♟'};
const names = {k:'king',q:'queen',r:'rook',b:'bishop',n:'knight',p:'pawn'};
const page = document.body.dataset.page;
let stats = {squares:0,positions:0,openings:0,tactics:0};
try { stats = {...stats,...JSON.parse(localStorage.getItem('chess-room-progress') || '{}')}; } catch {}
function record(key) { stats[key]++; try {localStorage.setItem('chess-room-progress',JSON.stringify(stats));} catch {} }
const nav = [['home','index.html','Practice'],['board','board.html','Board memory'],['openings','openings.html','Openings'],['tactics','tactics.html','Tactics']];
document.querySelector('#app').innerHTML = `<header><a class="brand" href="index.html"><span aria-hidden="true">♞</span> Chess Room</a><nav aria-label="Main navigation">${nav.map(([key,url,label])=>`<a href="${url}" ${key===page?'class="active" aria-current="page"':''}>${label}</a>`).join('')}</nav></header><main id="main"></main><footer><span>A little practice. A clearer board.</span><span>Progress saved on this device</span></footer>`;
const main = document.querySelector('#main');
function initial() {const b={}; for(let i=0;i<8;i++){b[files[i]+'1']='RNBQKBNR'[i];b[files[i]+'2']='P';b[files[i]+'7']='p';b[files[i]+'8']='rnbqkbnr'[i];} return b;}
function move(b,from,to){const p=b[from];delete b[from];b[to]=p;if(p?.toLowerCase()==='k' && Math.abs(files.indexOf(to[0])-files.indexOf(from[0]))===2){const rank=from[1],short=to[0]==='g';b[(short?'f':'d')+rank]=b[(short?'h':'a')+rank];delete b[(short?'h':'a')+rank];}}
function boardHTML(){return '<div class="board-wrap"><div id="board" class="chessboard" role="group" aria-label="Chess board"></div><div class="board-meta"><span id="board-caption">White’s perspective</span><button class="secondary" id="flip" type="button">Flip board ↻</button></div></div>';}
let position={}, flipped=false, showCoords=true, clickable=null, marked=[], selected=null;
function renderBoard(){const el=document.querySelector('#board');if(!el)return;const fs=flipped?[...files].reverse():[...files],rs=flipped?[1,2,3,4,5,6,7,8]:[8,7,6,5,4,3,2,1];el.innerHTML=rs.map((r,ri)=>fs.map((f,fi)=>{const sq=f+r,p=position[sq];return `<button type="button" class="square ${(files.indexOf(f)+r)%2===0?'dark':''} ${marked.includes(sq)?'marked':''} ${selected===sq?'selected':''}" data-square="${sq}" aria-label="${sq}${p?', '+(p===p.toUpperCase()?'white ':'black ')+names[p.toLowerCase()]:', empty'}">${p?`<span aria-hidden="true" class="piece ${p===p.toUpperCase()?'white':''}">${symbols[p]}</span>`:''}${showCoords&&ri===7?`<span class="coord" aria-hidden="true">${f}</span>`:''}${showCoords&&fi===0?`<span class="coord rank" aria-hidden="true">${r}</span>`:''}</button>`;}).join('')).join('');el.querySelectorAll('button').forEach(btn=>btn.onclick=()=>clickable?.(btn.dataset.square));}
function setupBoard(){document.querySelector('#flip').onclick=()=>{flipped=!flipped;renderBoard();document.querySelector('#board-caption').textContent=flipped?'Black’s perspective':'White’s perspective';};renderBoard();}
function feedback(message,success=false){const el=document.querySelector('#feedback');el.textContent=message;el.classList.toggle('success',success);}
function pick(items){return items[Math.floor(Math.random()*items.length)];}
if(page==='home'){
 main.innerHTML=`<section class="hero"><div><div class="pill"><span class="dot"></span> YOUR DAILY CHESS PRACTICE</div><div class="eyebrow">Train your mind, one square at a time</div><h1 style="margin-top:18px">See the board.<br>Know your next move.</h1><p>A quiet place to build your chess intuition. Memorize positions, learn your openings, and spot the tactics hiding in plain sight.</p><a class="button" href="board.html">Start practicing <span>↗</span></a></div>${boardHTML()}</section><section><div class="section-line"><h2>Choose your practice</h2><span>Small sessions. Lasting habits.</span></div><div class="cards">${[['01 / THE FOUNDATION','♙','Board memory','Know every square. Study a position, then rebuild it from memory.','board.html'],['02 / THE FIRST MOVES','♞','Opening repertoire','Explore classic openings and rehearse the moves until they feel familiar.','openings.html'],['03 / THE OPPORTUNITY','♜','Tactical vision','Find a mating move or a knight fork. Turn patterns into instinct.','tactics.html']].map(([n,icon,title,desc,url])=>`<a class="card" href="${url}"><div class="icon" aria-hidden="true">${icon}</div><small>${n}</small><h3>${title}</h3><p>${desc}</p><div class="go">Enter practice <span>↗</span></div></a>`).join('')}</div><div class="stats"><div><strong>${stats.squares}</strong>Squares found</div><div><strong>${stats.positions}</strong>Positions recalled</div><div><strong>${stats.openings+stats.tactics}</strong>Lines & puzzles solved</div></div></section>`;
 position={g1:'K',d1:'Q',a1:'R',f1:'R',c4:'B',f3:'N',a2:'P',b2:'P',c2:'P',d3:'P',e4:'P',f2:'P',g2:'P',h2:'P',g8:'k',d8:'q',a8:'r',f8:'r',c5:'b',c6:'n',a7:'p',b7:'p',c7:'p',d6:'p',e5:'p',f7:'p',g7:'p',h7:'p'}; setupBoard();
}
if(page==='board'){
 main.innerHTML=`<div class="practice-head"><div class="eyebrow">01 / The foundation</div><h1>Make the board familiar.</h1><p>Learn the squares. Then learn to hold a position in your mind.</p></div><div class="workspace">${boardHTML()}<section class="panel"><div class="controls"><button id="square-mode" class="active">Square names</button><button id="memory-mode">Position memory</button></div><div id="exercise"></div><div id="feedback" class="feedback" role="status" aria-live="polite"></div><p class="note">Tap squares to answer. Your correct exercises save automatically on this device.</p></section></div>`;
 let mode='square',target='',phase='',solution={},paint='K',timer=null,answered=false;
 function squares(){clearTimeout(timer);mode='square';position={};marked=[];selected=null;answered=false;target=pick([...files])+pick([1,2,3,4,5,6,7,8]);document.querySelector('#exercise').innerHTML=`<h2>Find the square</h2><p>Tap this square on the board.</p><div class="prompt">${target}</div><label><input type="checkbox" id="coordinates" ${showCoords?'checked':''}> Show coordinates</label><div class="controls"><button id="next-square">Next square →</button></div>`;document.querySelector('#coordinates').onchange=e=>{showCoords=e.target.checked;renderBoard();};document.querySelector('#next-square').onclick=squares;feedback('');renderBoard();}
 function memory(){clearTimeout(timer);mode='memory';phase='ready';showCoords=true;position={};marked=[];selected=null;document.querySelector('#exercise').innerHTML='<h2>Remember the position</h2><p>Study the pieces for a few seconds. When they disappear, put each piece back on its square.</p><label class="field" for="difficulty">Challenge</label><select id="difficulty"><option value="3">3 pieces · 8 seconds</option><option value="5">5 pieces · 12 seconds</option><option value="7">7 pieces · 16 seconds</option></select><div class="controls"><button id="study" class="primary">Study a position</button></div>';document.querySelector('#study').onclick=study;feedback('');renderBoard();}
 function study(){const count=Number(document.querySelector('#difficulty').value);solution={};const available=[...files].flatMap(f=>[2,3,4,5,6,7].map(r=>f+r));const pieces=['K','k','N','R','B','Q','p'];for(let i=0;i<count;i++){const square=available.splice(Math.floor(Math.random()*available.length),1)[0];solution[square]=pieces[i];}position={...solution};phase='study';document.querySelector('#exercise').innerHTML='<h2>Take a good look.</h2><p>This is a memory arrangement, rather than a game position. Notice each piece and its square.</p><div class="controls"><button id="ready" class="primary">I’m ready</button></div>';document.querySelector('#ready').onclick=reconstruct;renderBoard();timer=setTimeout(reconstruct,(count*2+2)*1000);}
 function reconstruct(){clearTimeout(timer);phase='recall';position={};document.querySelector('#exercise').innerHTML=`<h2>Rebuild the position</h2><p>Choose a piece, then tap its square. Tap a placed piece again to remove it.</p><div class="palette">${[...new Set(Object.values(solution))].map(p=>`<button data-piece="${p}" class="${p===p.toUpperCase()?'white':''}" aria-label="${p===p.toUpperCase()?'White':'Black'} ${names[p.toLowerCase()]}">${symbols[p]}</button>`).join('')}</div><div class="controls"><button class="primary" id="check">Check position</button><button id="reveal">Reveal answer</button><button id="again">New position</button></div>`;paint=Object.values(solution)[0];const palette=document.querySelectorAll('[data-piece]');function highlight(){palette.forEach(b=>b.classList.toggle('active',b.dataset.piece===paint));}palette.forEach(b=>b.onclick=()=>{paint=b.dataset.piece;highlight();});highlight();document.querySelector('#check').onclick=()=>{const correct=Object.keys(solution).length===Object.keys(position).length&&Object.entries(solution).every(([sq,p])=>position[sq]===p);if(correct){record('positions');phase='done';feedback('All pieces recalled. Nicely done! Start a new position when you’re ready.',true);document.querySelector('#check').disabled=true;}else feedback('Some pieces are missing or on different squares. Keep trying, or reveal the answer.');};document.querySelector('#reveal').onclick=()=>{position={...solution};phase='done';renderBoard();feedback('Here is the original position. Try a new one to keep practicing.');document.querySelector('#check').disabled=true;};document.querySelector('#again').onclick=memory;feedback('');renderBoard();}
 clickable=sq=>{if(mode==='square'){if(answered)return;if(sq===target){record('squares');answered=true;marked=[sq];feedback('Correct! Choose Next square to continue.',true);renderBoard();}else feedback(`That’s ${sq}. Try finding ${target}.`);}else if(phase==='recall'){if(position[sq]===paint)delete position[sq];else position[sq]=paint;renderBoard();}};
 document.querySelector('#square-mode').onclick=()=>{document.querySelector('#square-mode').classList.add('active');document.querySelector('#memory-mode').classList.remove('active');squares();};document.querySelector('#memory-mode').onclick=()=>{document.querySelector('#memory-mode').classList.add('active');document.querySelector('#square-mode').classList.remove('active');memory();};squares();setupBoard();
}
const openings=[
 {name:'Italian Game',idea:'Develop the bishop toward f7, bring your knights out, and prepare to castle.',moves:[['e2','e4','e4'],['e7','e5','e5'],['g1','f3','Nf3'],['b8','c6','Nc6'],['f1','c4','Bc4'],['f8','c5','Bc5']]},
 {name:'Ruy Lopez',idea:'The bishop pressures the knight defending e5. Develop steadily and get your king safe.',moves:[['e2','e4','e4'],['e7','e5','e5'],['g1','f3','Nf3'],['b8','c6','Nc6'],['f1','b5','Bb5'],['a7','a6','a6'],['b5','a4','Ba4'],['g8','f6','Nf6'],['e1','g1','O-O']]},
 {name:'Queen’s Gambit',idea:'Offer the c-pawn to challenge Black’s central d-pawn and open lines for your pieces.',moves:[['d2','d4','d4'],['d7','d5','d5'],['c2','c4','c4'],['e7','e6','e6'],['b1','c3','Nc3'],['g8','f6','Nf6']]},
 {name:'Sicilian Defense',idea:'Black answers e4 with c5, creating an unbalanced fight for the center.',moves:[['e2','e4','e4'],['c7','c5','c5'],['g1','f3','Nf3'],['d7','d6','d6'],['d2','d4','d4'],['c5','d4','cxd4'],['f3','d4','Nxd4'],['g8','f6','Nf6']]}
];
if(page==='openings'){
 main.innerHTML=`<div class="practice-head"><div class="eyebrow">02 / The first moves</div><h1>A familiar start.</h1><p>Walk through a classic opening, then replay its moves from memory.</p></div><div class="workspace">${boardHTML()}<section class="panel"><label class="field" for="opening">Your opening</label><select id="opening">${openings.map((o,i)=>`<option value="${i}">${o.name}</option>`).join('')}</select><h2 id="opening-title" style="margin-top:24px"></h2><p id="idea"></p><div id="moves" class="moves"></div><div class="controls"><button id="prev">← Back</button><button id="next" class="primary">Next move →</button><button id="rehearse">Practice from memory</button></div><div id="feedback" class="feedback" role="status" aria-live="polite"></div><p class="note">Practice both sides of one illustrative line. Other opening moves can also be good.</p></section></div>`;
 let opening=openings[0],step=0,practice=false;
 function update(){position=initial();for(let i=0;i<step;i++)move(position,...opening.moves[i]);marked=step?opening.moves[step-1].slice(0,2):[];selected=null;renderBoard();document.querySelector('#opening-title').textContent=opening.name;document.querySelector('#idea').textContent=opening.idea;document.querySelector('#moves').textContent=step?opening.moves.slice(0,step).map((m,i)=>(i%2===0?`${Math.floor(i/2)+1}. `:'')+m[2]).join(' '):'Starting position';document.querySelector('#prev').disabled=practice||step===0;document.querySelector('#next').disabled=practice||step===opening.moves.length;if(practice&&step<opening.moves.length)feedback(`${step%2===0?'White':'Black'} to move. Tap the piece, then its destination.`);}
 function reset(){opening=openings[Number(document.querySelector('#opening').value)];step=0;practice=false;update();feedback('Use Next move to study the line, or practice from memory.');}
 document.querySelector('#opening').onchange=reset;document.querySelector('#prev').onclick=()=>{step--;update();feedback('');};document.querySelector('#next').onclick=()=>{step++;update();feedback(step===opening.moves.length?'You’ve reached the end of this line. Try it from memory.':'');};document.querySelector('#rehearse').onclick=()=>{practice=true;step=0;update();};
 clickable=sq=>{if(!practice||step===opening.moves.length)return;if(!selected){if(!position[sq])return;selected=sq;renderBoard();return;}if(sq===selected){selected=null;renderBoard();return;}const [from,to]=opening.moves[step];if(selected===from&&sq===to){step++;update();if(step===opening.moves.length){record('openings');feedback('Complete! You remembered the whole line.',true);}}else{selected=null;renderBoard();feedback('That move isn’t in this practice line. Try again, or select the opening again to study it.');}};reset();setupBoard();
}
const scholar=initial();[['e2','e4'],['e7','e5'],['f1','c4'],['b8','c6'],['d1','h5'],['g8','f6']].forEach(m=>move(scholar,...m));
const puzzles=[
 {name:'The back rank',theme:'Mate in one',board:{g1:'K',e1:'R',g8:'k',f7:'p',g7:'p',h7:'p'},from:'e1',to:'e8',hint:'Black’s own pawns keep the king on the back rank.',explain:'Re8# controls the entire eighth rank. The black king has no escape square.'},
 {name:'The vulnerable f7 square',theme:'Mate in one',board:scholar,from:'h5',to:'f7',hint:'Find the square attacked by both your queen and bishop.',explain:'Qxf7# gives check next to the king. The bishop on c4 protects the queen, and Black cannot escape.'},
 {name:'A double attack',theme:'Knight fork',board:{g1:'K',e5:'N',g8:'k',d8:'q',h8:'r',g7:'p',h7:'p'},from:'e5',to:'f7',hint:'Put the knight where it attacks the queen and rook at the same time.',explain:'Nf7 forks the queen on d8 and rook on h8. One knight creates two threats.'}
];
if(page==='tactics'){
 main.innerHTML=`<div class="practice-head"><div class="eyebrow">03 / The opportunity</div><h1>Find the hidden move.</h1><p>Slow down, look for threats, and make the pattern yours.</p></div><div class="workspace">${boardHTML()}<section class="panel"><div class="eyebrow" id="theme"></div><h2 id="puzzle-title" style="margin-top:16px"></h2><p>White to move. Tap a piece, then tap its destination.</p><div class="controls"><button id="hint">Give me a hint</button><button id="answer">Show solution</button><button id="next-puzzle" class="primary">Next puzzle →</button></div><div id="feedback" class="feedback" role="status" aria-live="polite"></div><p class="note" id="puzzle-count"></p></section></div>`;
 let index=0,solved=false;function load(){const p=puzzles[index];position={...p.board};marked=[];selected=null;solved=false;document.querySelector('#theme').textContent=p.theme;document.querySelector('#puzzle-title').textContent=p.name;document.querySelector('#puzzle-count').textContent=`Puzzle ${index+1} of ${puzzles.length} · Starter collection`;feedback('Look for checks, captures, and threats.');renderBoard();}function finish(answer){const p=puzzles[index];move(position,p.from,p.to);marked=[p.from,p.to];selected=null;solved=true;renderBoard();if(!answer)record('tactics');feedback((answer?'Solution: ':'Correct! ')+p.explain,!answer);}
 document.querySelector('#hint').onclick=()=>{if(!solved)feedback(puzzles[index].hint);};document.querySelector('#answer').onclick=()=>{if(!solved)finish(true);};document.querySelector('#next-puzzle').onclick=()=>{index=(index+1)%puzzles.length;load();};clickable=sq=>{if(solved)return;const p=puzzles[index];if(!selected){if(!position[sq]||position[sq]!==position[sq].toUpperCase())return;selected=sq;renderBoard();return;}if(selected===sq){selected=null;renderBoard();return;}if(selected===p.from&&sq===p.to)finish(false);else{selected=null;renderBoard();feedback('Try another move. A hint can help you spot the pattern.');}};load();setupBoard();
}
